### ISSUE TITLE
uts插件，引入原生.aar文件，远程服务能成功绑定，为什么运行时找不到本地的aidl生成的接口文件

### ISSUE THREAD

**Issue by wuxaye** [dcloudio/hello-uniapp#103]
2024-08-03 22:06:24.574 10595-10595 AndroidRuntime          io.dcloud.HBuilder                   E  FATAL EXCEPTION: main
                                                                                                    Process: io.dcloud.HBuilder, PID: 10595
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/wif/baseservice/IBaseServiceInterface$Stub;
                                                                                                    	at uts.sdk.modules.wifService.BaseServiceConnection.onServiceConnected(index.kt:102)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1978)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2010)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wif.baseservice.IBaseServiceInterface$Stub" on path: DexPathList[[dex file "/storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni_modules/wif-service/utssdk/app-android/classes.dex", dex file "InMemoryDexFile[cookie=[0, 504360812720]]", zip file "/data/app/~~VRJnHZwJgUDKXCMx0pU0BQ==/io.dcloud.HBuilder-Hs8dpNA5VlD8qIl0FI0t0A==/base.apk"],nativeLibraryDirectories=[/data/app/~~VRJnHZwJgUDKXCMx0pU0BQ==/io.dcloud.HBuilder-Hs8dpNA5VlD8qIl0FI0t0A==/lib/arm64, /data/app/~~VRJnHZwJgUDKXCMx0pU0BQ==/io.dcloud.HBuilder-Hs8dpNA5VlD8qIl0FI0t0A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at uts.sdk.modules.wifService.BaseServiceConnection.onServiceConnected(index.kt:102) 
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1978) 
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2010) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by wuxaye** [comment]
我的问题，打包自定义插件就可以了
