### ISSUE TITLE
  at io.dcloud.feature.ad.dcloud.AdFeatureImpl.doForFeature(AdFeatureImpl.java:94)

### ISSUE THREAD

**Issue by yanchengdeng** [dcloudio/hello-uniapp#36]
AdFeatureImpl  这个类的变量  ：  registerHandler  空指针判断错误  

`
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.LinkedHashMap.entrySet()' on a null object reference
        at io.dcloud.feature.ad.dcloud.AdFeatureImpl.doForFeature(AdFeatureImpl.java:94)
        at io.dcloud.feature.ad.AdFeatureImplMgr.doForFeature(AdFeatureImplMgr.java:24)
        at io.dcloud.a.a(AdMgr.java:38)
        at io.dcloud.b.checkAndRequestStoragePermission(BaseActivity.java:180)
        at io.dcloud.WebAppActivity.checkAndRequestStoragePermission(WebAppActivity.java:82)
        at io.dcloud.b.onCreate(BaseActivity.java:127)
        at io.dcloud.WebAppActivity.onCreate(WebAppActivity.java:124)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
`

`
 public static Object doForFeature(String var0, Object var1) {
        Iterator var3;
        if ("onAppCreate".equals(var0)) {
            Context var2 = (Context)var1;
            Logger.p("doForFeature", "AdFeatureImpl onAppCreate");
            if (registerHandler == null || registerHandler.size() <= 0) {
                registerHandler = new LinkedHashMap();
                var3 = splashHandler.entrySet().iterator();

                while(var3.hasNext()) {
                    Entry var4 = (Entry)var3.next();

                    try {
                        Class var5 = Class.forName((String)var4.getValue());
                        registerHandler.put(var4.getKey(), (ADBaseHandler)var5.newInstance());
                    } catch (Exception var9) {
                    }
                }
            }

            StringBuilder var11 = new StringBuilder();
            Iterator var13 = registerHandler.entrySet().iterator();

            while(var13.hasNext()) {
                Entry var16 = (Entry)var13.next();
                ((ADBaseHandler)var16.getValue()).onCreate(var2);
                var11.append((String)var16.getKey()).append(",");
            }

            if (var11.length() > 0 && var11.lastIndexOf(",") == var11.length() - 1) {
                var11 = var11.deleteCharAt(var11.length() - 1);
            }

            HashMap var14 = new HashMap();
            var14.put("pspType", var11.toString());
            AdSplashUtil.saveOperate(var14);
        } else {
            Object[] var10;
            final Context var12;
            final String var15;
            if ("pull".equals(var0)) {
                mAdHandler = null;
                isSplashClose = false;
                var10 = (Object[])((Object[])var1);
                var12 = (Context)var10[0];
                var15 = (String)var10[1];
                Logger.p("doForFeature", "AdFeatureImpl pull");
                Iterator var17 = registerHandler.entrySet().iterator();

                while(var17.hasNext()) {
                    Entry var6 = (Entry)var17.next();
                    if (((String)var6.getKey()).equalsIgnoreCase("gdt")) {
                        ((ADBaseHandler)var6.getValue()).onCreate(var12);
                    } else {
                        ((ADBaseHandler)var6.getValue()).pullAds(var12);
                    }
                }

                ADHandler.pull(var12, var15, false, new IADReceiver[]{new ADReceiver(var12), new IADReceiver() {
                    public void onReceiver(JSONObject var1) {
                        if (var1.has("psp")) {
                            HashMap var2 = new HashMap();
                            var2.put("ad_list_order", var1.optString("psp"));
                            AdSplashUtil.saveOperate(var2);
                        } else {
                            SP.removeBundleData(ADHandler.AdTag, "ad_list_order");
                        }

                        AdFeatureImpl.isRequestSuccess = true;
                        if (var12 instanceof WebAppActivity) {
                            (new Handler(Looper.getMainLooper())).post(new Runnable() {
                                public void run() {
                                    ((WebAppActivity)var12).onCreateAdSplash(var12);
                                }
                            });
                        }

                        try {
                            JSONObject var15x = var1.optJSONObject("data");
                            HashMap var3 = new HashMap();
                            JSONObject var4 = new JSONObject();
                            if (var15x == null) {
                                var3.put("uniad", "");
                                var3.put("cad", "");
                            } else {
                                if (var15x.has("uniad")) {
                                    var3.put("uniad", var15x.optString("uniad"));
                                } else {
                                    var3.put("uniad", "");
                                }

                                if (!var15x.has("cad")) {
                                    var3.put("cad", "");
                                } else {
                                    JSONObject var5 = var15x.optJSONObject("cad");
                                    if (var5 != null) {
                                        Iterator var6 = var5.keys();

                                        while(true) {
                                            if (!var6.hasNext()) {
                                                var3.put("cad", var4.length() > 0 ? var4.toString() : "");
                                                break;
                                            }

                                            String var7 = (String)var6.next();
                                            JSONObject var8 = var5.getJSONObject(var7);
                                            JSONArray var9 = var8.getJSONArray("cls-a");

                                            for(int var10 = 0; var10 < var9.length(); ++var10) {
                                                String var11 = var9.getString(var10);

                                                try {
                                                    Class.forName(var11);
                                                    JSONObject var12x = new JSONObject();
                                                    var12x.put("r", "1");
                                                    var4.put(var7, var12x);
                                                } catch (Exception var13) {
                                                    break;
                                                }
                                            }
                                        }
                                    }
                                }
                            }

                            AdSplashUtil.saveOperate(var3);
                            if (var4.length() > 0) {
                                ADHandler.pullRad(var12, new IADReceiver[]{new ADReceiver(var12), new IADReceiver() {
                                    public void onReceiver(JSONObject var1) {
                                        if (var1.has("data")) {
                                            final JSONArray var2 = var1.optJSONArray("data");
                                            if (var2 != null && var2.length() > 0) {
                                                ((Activity)var12).runOnUiThread(new Runnable() {
                                                    public void run() {
                                                        checkPromptData(var2);
                                                    }
                                                });
                                            }
                                        }

                                    }

                                    public void checkPromptData(JSONArray var1) {
                                        try {
                                            if (var1.length() > 0) {
                                                for(int var2 = 0; var2 < var1.length(); ++var2) {
                                                    JSONObject var3 = var1.getJSONObject(var2);
                                                    if (var3 != null && var3.length() > 0) {
                                                        if (var3.optString("action").equals("prompt")) {
                                                            final String var4 = var3.optString("onclose");
                                                            AlertDialog var5 = (new Builder(var12)).setTitle(var3.optString("title")).setMessage(var3.optString("message")).setCancelable(false).setPositiveButton(17039370, new OnClickListener() {
                                                                public void onClick(DialogInterface var1, int var2) {
                                                                    if (var4.equals("exit")) {
                                                                        Process.killProcess(Process.myPid());
                                                                    } else {
                                                                        var1.dismiss();
                                                                    }

                                                                }
                                                            }).create();
                                                            var5.setCanceledOnTouchOutside(false);
                                                            var5.show();
                                                        } else if (var3.optString("action").equals("toast")) {
                                                            b var11 = new b((Activity)var12, "");
                                                            TextView var12x = new TextView(var12);
                                                            var12x.setAutoLinkMask(15);
                                                            var12x.setClickable(true);
                                                            var12x.setText(a.a(var12).a(var3.optString("message")));
                                                            LinearLayout var6 = new LinearLayout(var12);
                                                            var6.addView(var12x);
                                                            var11.a(var6, var12x);
                                                            var11.setDuration(1);
                                                            var11.setGravity(80, var11.getXOffset(), var11.getYOffset());
                                                            int var7 = CanvasHelper.dip2px(var12, 10.0F);
                                                            int var8 = CanvasHelper.dip2px(var12, 8.0F);
                                                            var6.setPadding(var7, var8, var7, var8);
                                                            GradientDrawable var9 = new GradientDrawable();
                                                            var9.setCornerRadius((float)var8);
                                                            var9.setShape(0);
                                                            var9.setColor(-1308622848);
                                                            var6.setBackground(var9);
                                                            var12x.setGravity(17);
                                                            var12x.setTextColor(Color.parseColor("#ffffffff"));
                                                            var11.show();
                                                        }
                                                    }
                                                }
                                            }
                                        } catch (Exception var10) {
                                        }

                                    }

                                    public void onError(String var1, String var2) {
                                    }
                                }});
                            }
                        } catch (Exception var14) {
                        }

                    }

                    public void onError(String var1, String var2) {
                        HashMap var3 = new HashMap();
                        var3.put("uniad", "");
                        AdSplashUtil.saveOperate(var3);
                        Logger.p("request Fail", "type:" + var1 + ";message:" + var2);
                        AdFeatureImpl.mHandler.postDelayed(new Runnable() {
                            public void run() {
                                io.dcloud.a.a(var12, var15, "pull", (Object)null);
                            }
                        }, 60000L);
                    }
                }});
            } else if ("save".equals(var0)) {
                var10 = (Object[])((Object[])var1);
                var12 = (Context)var10[0];
                var15 = (String)var10[1];
                HashMap var20 = (HashMap)var10[2];
                Logger.p("doForFeature", "AdFeatureImpl save");
                AdSplashUtil.saveOperate(var12, var15, var20);
            } else {
                if ("formatUrl_wanka".equals(var0)) {
                    var10 = (Object[])((Object[])var1);
                    Object[] var21 = (Object[])((Object[])var10[2]);
                    var15 = (String)var21[0];
                    JSONObject var25 = (JSONObject)var21[1];
                    Logger.p("doForFeature", "AdFeatureImpl formatUrl_wanka");
                    return ADHandler.formatUrl(var15, var25);
                }

                if ("handleArgs_wanka".equals(var0)) {
                    var10 = (Object[])((Object[])var1);
                    JSONObject var18 = (JSONObject)var10[2];
                    Logger.p("doForFeature", "AdFeatureImpl handleArgs_wanka");
                    return ADHandler.getArgsJsonData(var18);
                }

                if ("onWillCloseSplash".equals(var0)) {
                    isSplashClose = true;
                    isRequestSuccess = false;
                    var10 = (Object[])((Object[])var1);
                    Logger.p("doForFeature", "AdFeatureImpl onWillCloseSplash");
                    if (var10[2] != null && var10[2] instanceof View && mAdHandler != null) {
                        mAdHandler.onSplashClose((View)var10[2]);
                    }

                    var3 = registerHandler.values().iterator();

                    while(var3.hasNext()) {
                        ADBaseHandler var19 = (ADBaseHandler)var3.next();
                        var19.clearListener();
                    }

                    mAdHandler = null;
                } else if ("onCreateAdSplash".equals(var0)) {
                    if (!isRequestSuccess) {
                        return null;
                    }

                    if (mAdHandler != null) {
                        return null;
                    }

                    if (isSplashClose) {
                        return null;
                    }

                    var10 = (Object[])((Object[])var1);
                    var12 = (Context)var10[0];
                    if (!ADHandler.SplashAdIsEnable(var12)) {
                        return null;
                    }

                    ICallBack var22 = (ICallBack)var10[1];
                    String var23 = (String)var10[2];
                    var23 = TextUtils.isEmpty(var23) ? ADHandler.appid(var12) : var23;
                    String var24 = ADHandler.get("uniad");
                    if (TextUtils.isEmpty(var24)) {
                        mAdHandler = new DcloudHandler();
                        return mAdHandler.onCreateSplash(var12, var23, var22);
                    }

                    String var8 = AdSplashUtil.getSplashAdpId((IApp)null, "_psp_", (String)null);
                    Object var7;
                    if (TextUtils.isEmpty(var8)) {
                        var7 = AdSplashUtil.getAdOrder();
                    } else {
                        var7 = new ArrayList(Arrays.asList(var8.split(",")));
                    }

                    ((List)var7).remove("");
                    if (((List)var7).contains("dcloud") && registerHandler.get("dcloud") != null && registerHandler.get("dcloud") instanceof DcloudHandler) {
                        ((DcloudHandler)registerHandler.get("dcloud")).initAdData(var12, var23);
                    }

                    Logger.p("doForFeature", "AdFeatureImpl onCreateAdSplash");
                    if (((List)var7).size() > 0) {
                        if (PermissionUtil.isEMUIRom((Activity)var12) && VERSION.SDK_INT >= 26 && ((List)var7).size() > 1 && ((String)((List)var7).get(0)).equals("csj") && PermissionUtil.checkSelfPermission((Activity)var12, "android.permission.READ_PHONE_STATE") != 0) {
                            Collections.shuffle((List)var7);
                        }

                        mAdHandler = checkSplashView((List)var7, var12);
                        if (mAdHandler != null) {
                            return mAdHandler.onCreateSplash(var12, var23, var22);
                        }
                    }
                } else if ("onAppAttachBaseContext".equals(var0)) {
                    Logger.p("doForFeature", "AdFeatureImpl onAppAttachBaseContext");
                }
            }
        }

        return null;
    }

`

这里的 registerHandler  判断空指针的   if  else  错误

**Comment by yanchengdeng** [comment]
最后是导入包错误导致，但是空指针判断是真实存在的 ，还是希望更改下！
