### ISSUE TITLE
sass-loader报错

### ISSUE THREAD

**Issue by IanLew** [dcloudio/hello-uniapp#64]
@vue/cli 4.5.15 通过命令拉取下来，HbuilderX 3.3.5 编译sass-loader报错
```bash
vue create -p dcloudio/uni-preset-vue my-project
```
sass-loader配置错误，sass-loader 7.3.1，错误信息：
```
Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
  - options has an unknown property 'data'. These properties are valid:
    object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter?, nvue? }
     at validate (D:\liu-workspace\uniapp\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\node_modules\schema-utils\dist\validate.js:96:11)
     at Object.loader (D:\liu-workspace\uniapp\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\dist\index.js:38:28)
```

**Comment by codexu** [comment]
npm install --save-dev sass-loader@7.1.0

**Comment by codexu** [comment]
请升级 HBuilderX 到最新版本，3.5.3 版本未能复现此报错

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
